# The input folder containing the pre and post synaptic data, and the image of the synapses
# All three files are required for the program to run, and they must be labelled as follows:
INPUT_FOLDER_NAME = "input"

# Name of the file containing the pre-synaptic neuron data generated by CellProfiler
PRE_SYNAPSE_FILE_NAME = "pre.csv"

# Name of the file containing the post-synaptic neuron data generated by CellProfiler
POST_SYNAPSE_FILE_NAME = "post.csv"

# Name of the file containing the initial image of the synapses
IMAGE_FILE_NAME = "image.png"

# The output folder containing density/synapse image output and generated excel file output showing the calculations for the synapses
OUTPUT_FOLDER_NAME = "output"

# Name of the file containing the density image generated by densityAnalyser.py
DENSITY_IMAGE_FILE_NAME = "densityImage.png"

# Name of the file containing an image of the synapses generated by showSynapse.py
SYNAPSE_IMAGE_FILE_NAME = "synapseImage.png"

# Name of the file containing the synapse data generated by showSynapse.py
SYNAPSE_DATA_FILE_NAME = "synapseData.xlsx"

# Defines the number of pixels in each block of the density grid.
# The higher the number, the larger the squares will be, which may be useful for images with sparse points
GRIDSIZE = 100

# Colour of displayed points on the png image and the interactive visualization in RGB format
POINTS_COLOUR = (0, 255, 255)
# Colour of the brightest grid in the density map in RGB format
DENSITY_COLOUR = (255, 255, 255)

# Both threshold below used to filter out the pre-synaptic and post-synaptic points which don't show up in the initial image
# Defines how far away a colour should be (in distance to the exact RGB colouring) before it's no longer counted as red or green
COLOUR_THRESHOLD = 150
# Defines the distance we must find a red and green pixel in the image for the point to be counted as a synapse
DISTANCE_THRESHOLD = 2

# Both thresholds below used to filter out the synapse if the pre-synaptic and post-synaptic points are too far away or too close to each other
PRE_POST_DIST_LOWER_THRESHOLD = -2
PRE_POST_DIST_UPPER_THRESHOLD = 3
